# CONCEPTO BÁSICOS DE NUMPY

Para instalar Numpy se usa el siguiente comando:  conda install numpy

Numpy es un paquete elaborado en C que permite el analisis numerico con Python, similar a Matlab.  Permite el manejo de Arrays (Vectores o arreglos) de manera eficiente.

# NUMPY ARRAYS

En primer lugar se importa la libreria numpy con el alias de np.  Puede usarse cualquier alias, sin embargo por convención se utilizan np.

## Crear Numpy Arrays

In [2]:
import numpy as np

crear un numpy array es muy fácil, se puede crear transformando listas de Python

In [3]:
my_list = [1,2,3,4,5]
my_array = np.array(my_list)

In [4]:
type(my_list)

list

In [5]:
type(my_array)

numpy.ndarray

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
#python
list(range(0,5))

[0, 1, 2, 3, 4]

In [11]:
#numpy
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [12]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [13]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [14]:
np.zeros((4,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [15]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [22]:
np.linspace(0,10,20)

array([  0.        ,   0.52631579,   1.05263158,   1.57894737,
         2.10526316,   2.63157895,   3.15789474,   3.68421053,
         4.21052632,   4.73684211,   5.26315789,   5.78947368,
         6.31578947,   6.84210526,   7.36842105,   7.89473684,
         8.42105263,   8.94736842,   9.47368421,  10.        ])

In [3]:
np.eye(6)  #crea una matriz identidad de tamaño 6x6

array([[ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.]])

In [4]:
np.random.rand(1) #genera un numero aleatorio de una ditribución uniforme entre 0 y 1

array([ 0.46686192])

In [6]:
np.random.rand(3,4) #matriz de numeros aleatorios de una ditribución uniforme entre 0 y 1

array([[ 0.9036054 ,  0.29420943,  0.96486479,  0.08390753],
       [ 0.51921929,  0.67040705,  0.04357035,  0.27851933],
       [ 0.22736304,  0.4807144 ,  0.88728686,  0.2207768 ]])

In [7]:
np.random.randn(5) #genera 5 numeros aleatorios de una distribución normal (0,1)

array([-0.27587896, -1.17502409,  1.6953172 , -0.95139631, -0.73456501])

In [11]:
np.random.randint(1,100, 15) #genera 15 números aleatorio entre 1 y 100 (uniforme)

array([75, 57, 30, 66, 76, 25, 44, 69, 35, 52, 49, 48, 25,  4, 67])

In [13]:
array1 = np.arange(25)

In [18]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [19]:
array1.reshape(5,5) #convierte un vector de 25 elementos un una matriz 5x5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [21]:
array1.shape

(25,)

In [22]:
array1.reshape(5,5).shape

(5, 5)

In [23]:
array1.dtype

dtype('int32')