# CONCEPTO BÁSICOS DE NUMPY

Para instalar Numpy se usa el siguiente comando:  conda install numpy

Numpy es un paquete elaborado en C que permite el analisis numerico con Python, similar a Matlab.  Permite el manejo de Arrays (Vectores o arreglos) de manera eficiente.

# NUMPY ARRAYS

En primer lugar se importa la libreria numpy con el alias de np.  Puede usarse cualquier alias, sin embargo por convención se utilizan np.

## Crear Numpy Arrays

In [1]:
import numpy as np

crear un numpy array es muy fácil, se puede crear transformando listas de Python

In [3]:
my_list = [1,2,3,4,5]
my_array = np.array(my_list)

In [4]:
type(my_list)

list

In [5]:
type(my_array)

numpy.ndarray

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
#python
list(range(0,5))

[0, 1, 2, 3, 4]

In [11]:
#numpy
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [12]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [13]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [14]:
np.zeros((4,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [15]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [22]:
np.linspace(0,10,20)

array([  0.        ,   0.52631579,   1.05263158,   1.57894737,
         2.10526316,   2.63157895,   3.15789474,   3.68421053,
         4.21052632,   4.73684211,   5.26315789,   5.78947368,
         6.31578947,   6.84210526,   7.36842105,   7.89473684,
         8.42105263,   8.94736842,   9.47368421,  10.        ])